
name: Build, Run, and Test Flask App

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t flask-demo .

      - name: Run container and show output
        run: |
          docker run -d -p 5000:5000 flask-demo

      - name: Test app endpoint
        run: |
          curl http://localhost:5000

      - name: Run container detached and fetch logs
        run: |
          docker run -d -p 8080:8080 flask-demo
          CONTAINER_ID=$(docker ps -q --latest)
          docker logs $CONTAINER_ID
