name: Docker App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout (same as Jenkins git step)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      # Build Docker image
      - name: Build Docker image
        run: docker build -t myapp:latest .

      # Run Docker container
      - name: Run Docker container
        run: docker run -d -p 8080:8080 myapp:latest
