name: Docker Flask App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image (no cache)
        run: |
          docker build --no-cache -t flask-app .

      - name: Run Flask container
        run: |
          docker run -d -p 5000:5000 --name flask-test flask-app
          sleep 5

      - name: Call Flask app (SEE OUTPUT)
        run: |
          echo "Calling Flask endpoint..."
          curl http://localhost:5000

      - name: Show container logs
        run: |
          docker logs flask-test

  