name: Docker Flask App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image (no cache)
        run: |
          docker build --no-cache -t flask .

      - name: Run Flask container
        run: |
          docker run -d -p 5000:5000 --name flask-test flask
          sleep 5
          docker ps -a
          docker logs flask-test
