name: Docker App Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Build Image
        run: docker build -t myapp:latest .

      - name: Run Container
        run: docker run -d --name myapp-container -p 8080:5000 myapp:latest

      - name: Wait for app
        run: sleep 5

      - name: Show output (THIS is what you want)
        run: curl http://localhost:8080
